apiVersion: v1
kind: Service
metadata:
  name: dgs
  labels:
    app: dgs
spec:
  ports:
    - port: 32003
      targetPort: 8888
  clusterIP: None
  selector:
    app: dgs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dgs
spec:
  selector:
    matchLabels:
      app: dgs # has to match .spec.template.metadata.labels
  serviceName: "dgs"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: dgs # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: dgs
          image: hkccr.ccs.tencentyun.com/tke_cluster/tke_cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
              protocol: UDP
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      nodeSelector:
        environment: dev
#        - name: nginx
#          image: k8s.gcr.io/nginx-slim:0.8
#          ports:
#            - containerPort: 80
#              name: web
#          volumeMounts:
#            - name: www
#              mountPath: /usr/share/nginx/html
#  volumeClaimTemplates:
#    - metadata:
#        name: www
#      spec:
#        accessModes: [ "ReadWriteOnce" ]
#        storageClassName: "my-storage-class"
#        resources:
#          requests:
#            storage: 1Gi